# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d150dac605029d1e30ee7c7ded69fd0195a728ce69e8b9cb25146b3fb8edf20cf43b6caab9209680a63402e81f50faa12ceb1913665b2850d807e1acf55669cc

test:
  secret_key_base: 1c1fea914d70513ac6aec3b308d8ae0db935101b86aec1ec62097c0fe6dee6939c7bc87ad643846acd3ed8ad4bacae9b0643a9b61d8f04378fa510b80d75400e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
